"""empty message

Revision ID: 9858cde0a04a
Revises: 7915281ba69e
Create Date: 2018-12-04 15:00:08.007150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9858cde0a04a'
down_revision = '7915281ba69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'image')
    # ### end Alembic commands ###
